name: psoraseq_env
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - mamba
  - python=3
  - bowtie2
  - samtools
  - pip
  - pip:
    - pyarrow
    - pandas
    - numpy
    - pysam
    - scipy
    - seaborn
    - matplotlib
    - argparse
